# 错误处理

当发生错误时, 比如脚本解析错误, php将会进入到bailout模式. 在你已经看到的简单 的嵌入式例子中, 这表示它将直接跳到PHP_EMBED_END_BLOCK()宏, 并且绕过所有这个块中的剩余代码. 由于多数潜入php解释器的应用, 目的并不只是为了执行php代码, 因 此避免由于php脚本的故障导致整个应用崩溃是有意义的.
有⼀种方式可以将所有的执行限制到一个非常小的START/END块中, 这样发生崩溃 就只影响当前块. 这种方式的缺点是每个START/END块函数都是独立的PHP请求. 因此比 如下面START/END块, 虽然从语法逻辑上来看两个块是协同工作的, 但实际上它们之间是不共享公共作用域的.

````c
int main(int argc, char *argv[]){    PHP_EMBED_START_BLOCK(argc, argv)        zend_eval_string("$a = 1;", NULL, "Script Block 1");    PHP_EMBED_END_BLOCK()    PHP_EMBED_START_BLOCK(argc, argv)/* 将打印出"NULL", 因为变量$a在这个请求中并没有定义. */        zend_eval_string("var_dump($a);", NULL, "Script Block 2");    PHP_EMBED_END_BLOCK()    return 0;}
````

还有一种解决方法是将两个zend_eval_string()调用使用Zend特有的伪语言结构 zend_try, zend_catch, zend_end_try进行隔离. 使用这些结构, 你的应用就可以按照想要的方式处理错误. 考虑下面的代码:

````c
int main(int argc, char *argv[]){    PHP_EMBED_START_BLOCK(argc, argv)        zend_try {/* 尝试执行⼀一些可能失败的代码 */            zend_eval_string("$1a = 1;", NULL, "Script Block 1a");        } zend_catch {/* 发生错误, 则尝试执行另外⼀一部分代码(⼀一般错误的补救或报告等行为) */zend_eval_string("$a = 1;", NULL, "Script Block 1");} zend_end_try();/* 这里将显示"NULL", 因为变量$a在这个请求中没有定义. */ zend_eval_string("var_dump($a);", NULL, "Script Block 2");    PHP_EMBED_END_BLOCK()return 0; }
````

在这个示例的第二个版本中, zend_try块中将发生解析错误, 但它只影响自己的代码 块, 同时在zend_catch块中使用了⼀段好的代码对错误进行了处理. 同样你也可以尝试自 己给var_dump()部分也加上这些块.

````c
译注: 这里对zend_try/zend_catch/zend_end_try解释的不是很清楚, 因此做以下补充说明. 读 者阅读这一部分内容需要首先了解sigsetjmp()/siglongjmp()的机制(可以参考<Unix环境高级编程> 第10章第15节).相关的定义如下:
#ifdef HAVE_SIGSETJMP#   define SETJMP(a) sigsetjmp(a, 0)#   define LONGJMP(a,b) siglongjmp(a, b)#   define JMP_BUF sigjmp_buf#else#   define SETJMP(a) setjmp(a)#   define LONGJMP(a,b) longjmp(a, b)#   define JMP_BUF jmp_buf#endif#define zend_try 	\ 
{					\
	JMP_BUF *__orig_bailout = EG(bailout);                  \    JMP_BUF __bailout;                                      \                                                                \    EG(bailout) = &__bailout;                               \    if (SETJMP(__bailout)==0) {#define zend_catch                                              \        } else {                                                \            EG(bailout) = __orig_bailout;#define zend_end_try() \ }\ EG(bailout) = __orig_bailout; \}````
zend_try{}代码块中的代码是在一个if语句中的, 这个if的条件是SETJMP(__bailout) == 0, SETJMP()是在当前程序执行的点设置一个可回溯的点(保存了当前执行上下文和环境), SETJMP() 的返回比较特殊, 它有两种返回: 1) 直接返回, 此时返回值为0; 2) 调用LONGJMP()返回到对应 __bailout当时调用SETJMP()的位置, 此时返回值非0.
基于上面的论述, 可以看出, 当zend_try的代码块中调用了LONGJMP()的时候, 程序将回到if ( SETJMP(__bailout) == 0 )的位置开始执行, 并且它的返回值为-1, 因此, 进入到对应的else语句 块, 也就是zend_catch语句块的代码.
zend_end_try()则只是⼀个结尾的花括号.
php中的这个伪语言结构正式这种方式实现的异常处理机制, 在系统的关键点调用 zend_bailout()(在Zend/zend.h中定义)即可.
本例中, 译者增加了zend_bailout()调用, 演示了这个伪语言结构的使用.

## links
   * [目录](<preface.md>)
   * 20.1 [回调到php中](<20.1.md>)
   * 20.3 [初始化php](<20.3.md>)
